import { useState } from 'react';
import { useLoanStore } from '../../../store/useLoanStore';
import { ArrowRight, Activity, CheckCircle2 } from 'lucide-react';

interface OffersWidgetProps {
  onSelect?: (lenderId: string) => void;
}

export default function OffersWidget({ onSelect }: OffersWidgetProps) {
  const { loanDetails, setState } = useLoanStore();
  const [selectedOffer, setSelectedOffer] = useState<number | null>(null);

  // Mock offers generated by the platform AI
  const offers = [
    {
      id: 1,
      lender_id: 'HDFC_001',
      lender: 'HDFC Bank NBFC',
      amount: loanDetails.requestedAmount,
      roi: 10.5,
      emi: Math.round((loanDetails.requestedAmount * 1.105) / loanDetails.tenureMonths),
      tag: 'Best Rate'
    },
    {
      id: 2,
      lender_id: 'BAJAJ_002',
      lender: 'Bajaj Finance',
      amount: loanDetails.requestedAmount,
      roi: 11.2,
      emi: Math.round((loanDetails.requestedAmount * 1.112) / loanDetails.tenureMonths),
      tag: 'Fast Disbursal'
    },
    {
      id: 3,
      lender_id: 'MUTHOOT_003',
      lender: 'Muthoot Capital',
      amount: loanDetails.requestedAmount,
      roi: 12.0,
      emi: Math.round((loanDetails.requestedAmount * 1.120) / loanDetails.tenureMonths),
    }
  ];

  const handleAccept = (lenderId: string) => {
    setState('ACTIVE_LOAN');
    if (onSelect) onSelect(lenderId);
  };

  return (
    <div className="w-full max-w-2xl relative z-10 group">
      <div className="flex gap-4 overflow-x-auto pb-4 snap-x no-scrollbar">
        {offers.map((offer) => (
          <div 
            key={offer.id} 
            onClick={() => setSelectedOffer(offer.id)}
            className={`min-w-[280px] snap-center p-6 rounded-2xl border cursor-pointer transition-all duration-300 relative overflow-hidden flex-shrink-0 ${
              selectedOffer === offer.id 
                ? 'bg-[#111] border-white shadow-xl shadow-white/5' 
                : 'bg-[#0A0A0A] border-white/10 hover:border-white/30'
            }`}
          >
            {selectedOffer === offer.id && (
               <div className="absolute top-4 right-4">
                  <CheckCircle2 className="w-5 h-5 text-white" />
               </div>
            )}
            
            <div className="flex items-center gap-2 mb-6">
              <div className="w-10 h-10 rounded-lg bg-white/5 flex items-center justify-center font-display font-bold text-sm text-white border border-white/10">
                {offer.lender.substring(0, 1)}
              </div>
              <div>
                <h4 className="font-bold text-lg text-white leading-tight">{offer.lender}</h4>
                {offer.tag && (
                  <span className="text-[10px] font-bold text-emerald-500 uppercase tracking-widest">
                    {offer.tag}
                  </span>
                )}
              </div>
            </div>
            
            <div className="space-y-3 mb-6">
               <div className="flex justify-between items-center border-b border-white/5 pb-2">
                  <span className="text-xs text-white/50 uppercase tracking-widest">ROI</span>
                  <span className="font-medium text-white">{offer.roi}%</span>
               </div>
               <div className="flex justify-between items-center border-b border-white/5 pb-2">
                  <span className="text-xs text-white/50 uppercase tracking-widest">EMI</span>
                  <span className="font-medium text-white">₹{offer.emi.toLocaleString('en-IN')}</span>
               </div>
            </div>

            <button 
               onClick={(e) => {
                  e.stopPropagation();
                  setSelectedOffer(offer.id);
                  handleAccept(offer.lender_id);
               }}
               className={`w-full py-2.5 rounded-lg text-sm font-medium transition-all ${
                  selectedOffer === offer.id 
                     ? 'bg-white text-black' 
                     : 'bg-white/5 text-white hover:bg-white/10'
               }`}
            >
               {selectedOffer === offer.id ? 'Execute Smart Contract' : 'Select Partner'}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}
